changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes and Hardening
      labels:
        - bug
        - security
        - hardening
    - title: Documentation and Maintenance
      labels:
        - documentation
        - chore
        - refactor
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
